language: cpp
sudo: requiered
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libbz2-dev
      - libwebp-dev
install:
  - export CXX=g++-5
  - export CC=gcc-5
  - g++ --version
  - gcc --version
  - wget https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz
  - tar xzf cmake-3.5.1.tar.gz
  - cd cmake-3.5.1
  - ./bootstrap --no-qt-gui --parallel=2
  - make -j2
  - sudo make install
  - cd ..
  - git clone -b master https://github.com/opencv/opencv.git
  - cd opencv
  - git reset --hard e0435d3b8a871b54f9a78bb8662e47e47c36b05c
  - cmake ./ -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DWITH_IPP=OFF
  - make -j2
  - sudo make install
  - cd ../
script:
  - mkdir build
  - cd build
  - cmake ../ -DWITH_CUDA=OFF
  - make -j2
branches:
  only:
    - master
notifications:
  email: false
